// Primitive data types in JavaScript include:

// Numbers - Integers, floats
// Strings - Any data under single quote, double quote or backtick quote
// Booleans - true or false value
// Null - empty value or no value
// Undefined - a declared variable without a value
// Symbol - A unique value that can be generated by Symbol constructor

// let word = 'JavaScript'           //immutable
// let numOne = 3
// let numTwo = 3

// console.log(numOne == numTwo)      // true

// let js = 'JavaScript'
// let py = 'Python'

// console.log(js == py)             //false 

// let lightOn = true
// let lightOff = false

// console.log(lightOn == lightOff) // false

// --------------------------------------------------------------------------------------------------------------------

// Non-primitive data types in JavaScript includes:

// Objects
// Arrays

// let nums = [1, 2, 3]
// let numbers = [1, 2, 3]

// console.log(nums == numbers)  // false

// let userOne = {
// name:'Asabeneh',
// role:'teaching',
// country:'Finland'
// }

// let userTwo = {
// name:'Asabeneh',
// role:'teaching',
// country:'Finland'
// }

// console.log(userOne == userTwo) // false

// --------------------------------------------------Number Data Type----------------------------------------------------------------------

// Declaring Number Data Types
// let age = 35
// const gravity = 9.81  // we use const for non-changing values, gravitational constant in  m/s2
// let mass = 72         // mass in Kilogram
// const PI = 3.14       // pi a geometrical constant

// // More Examples
// const boilingPoint = 100 // temperature in oC, boiling point of water which is a constant
// const bodyTemp = 37      // oC average human body temperature, which is a constant

// console.log(age, gravity, mass, PI, boilingPoint, bodyTemp)

//----------------------------------------------------String------------------------------------------------------------------------

// Strings are texts, which are under single , double, back-tick quote. To declare a string, we need a variable name, assignment operator, a value under a single quote, double quote, or backtick quote. Let's see some examples of strings:

// let space = ' '           // an empty space string
// let firstName = 'Asabeneh'
// let lastName = 'Yetayeh'
// let country = 'Finland'
// let city = 'Helsinki'
// let language = 'JavaScript'
// let job = 'teacher'
// let quote = "The saying,'Seeing is Believing' is not correct in 2020."
// let quotWithBackTick = `The saying,'Seeing is Believing' is not correct in 2020.`

//--> String Concatenation
// let fullName = firstName + space + lastName; // concatenation, merging two string together.
// console.log(fullName);

// -->Concatenating Using Addition Operator
// let fullName =firstName + space + lastName
// let personInfoOne = fullName + '. I am ' + age + '. I live in ' + country; // ES5 string addition
// console.log(personInfoOne)

// -->Concatenating Using Template Literals
// let personInfoTwo = `I am ${fullName}. I am ${age}. I live in ${country}.`; //ES6 Template literals or interpolation
// console.log(personInfoTwo)

//-->Escape Sequences in Strings
// console.log('I hope everyone is enjoying the 30 Days Of JavaScript challenge.\nDo you ?') // line break
// console.log('Days\tTopics\tExercises')
// console.log('Day 1\t3\t5')
// console.log('Day 2\t3\t5')
// console.log('Day 3\t3\t5')
// console.log('Day 4\t3\t5')

// ----------------------------------------------------String Method------------------------------------------------------------------

// length
// let js = 'JavaScript'
// console.log(js.length)         // 10

// Accessing characters in a string
// let string = 'JavaScript'
// let firstLetter = string[0]
// console.log(firstLetter)           // J

// toUpperCase()
// let string = 'JavaScript'
// console.log(string.toUpperCase())     // JAVASCRIPT

// toLowerCase()
// let string = 'JavaScript'
// console.log(string.toLowerCase())     // javascript

// substr()
// let string = 'JavaScript'
// console.log(string.substr(4,6))       // Script
// console.log(string.substr(0,5))       // JavaScri

// substring()
// let string = 'JavaScript'
// console.log(string.substring(0,4))    // Java
// console.log(string.substring(4,10))   // Script

// split()
// let string = '30 Days Of JavaScript'
// console.log(string.split())           // ["30 Days Of JavaScript"]
// console.log(string.split(' '))        // ["30", "Days", "Of", "JavaScript"]

// includes()
// let string = '30 Days Of JavaScript'
// console.log(string.includes('Days'))  // true
// console.log(string.includes('days'))  // false

// replace()
// let string = '30 Days Of JavaScript'
// console.log(string.replace('JavaScript', 'Python'))  // 30 Days Of Python

// charAt()
// let string = 'JavaScript'
// console.log(string.charAt(0))         // J

// --------------------------------------------------Checking Data Types and Casting-----------------------------------------------------------

// typeof operator
// let firstName = 'Asabeneh'
// console.log(typeof 'Asabeneh')  // string

// let age = 100
// console.log(typeof age)         // number

// let isMarried = true
// console.log(typeof isMarried)   // boolean

// ----------------------------------------------------Changing Data Type (Casting)----------------------------------------------------
// let age = 100
// console.log(typeof age)         // number
// console.log(age.toString())     // "100"
// console.log(typeof age.toString()) // string
// console.log(age.toString(2))    // "1100100"
// console.log(age.toString(8))    // "144"

// let number = '100'
// console.log(number)              // "100"
// console.log(typeof number)       // string
// console.log(Number(number))      // 100
// console.log(typeof Number(number)) // number
// console.log(Number(number) + 1)  // 101
